"""Forward-only SQL migration runner.

Usage: `python -m app.db.migrate`

No Alembic: the schema is hand-written DDL owned by
`03_Database/01_PostgreSQL_Schema.md`, and autogenerated diffs from an ORM the
project does not have would only fight it. Files are applied in filename order
and recorded in `schema_migrations`; each file is also written to be internally
idempotent, so a database left half-migrated by a crash still converges.
"""

import asyncio
import hashlib
import logging
from pathlib import Path

import asyncpg

from app.core.config import get_settings
from app.core.logging import configure_logging

logger = logging.getLogger("app.db.migrate")

MIGRATIONS_DIR = Path(__file__).parent / "migrations"

LEDGER_DDL = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""


def migration_files(directory: Path = MIGRATIONS_DIR) -> list[Path]:
    return sorted(directory.glob("*.sql"))


async def apply_migrations(dsn: str | None = None) -> list[str]:
    """Apply every pending migration. Returns the versions applied this run."""
    dsn = dsn or get_settings().database_url
    conn = await asyncpg.connect(dsn)
    applied: list[str] = []
    try:
        await conn.execute(LEDGER_DDL)
        known = {row["version"] for row in await conn.fetch("SELECT version FROM schema_migrations")}

        for path in migration_files():
            version = path.stem
            if version in known:
                logger.info("migration already applied", extra={"version": version})
                continue

            sql = path.read_text(encoding="utf-8")
            checksum = hashlib.sha256(sql.encode()).hexdigest()
            async with conn.transaction():
                await conn.execute(sql)
                await conn.execute(
                    "INSERT INTO schema_migrations (version, checksum) VALUES ($1, $2)"
                    " ON CONFLICT (version) DO NOTHING",
                    version,
                    checksum,
                )
            applied.append(version)
            logger.info("migration applied", extra={"version": version})
    finally:
        await conn.close()
    return applied


def main() -> None:
    settings = get_settings()
    configure_logging(settings.log_level)
    applied = asyncio.run(apply_migrations(settings.database_url))
    logger.info("migrations up to date", extra={"applied": applied, "count": len(applied)})


if __name__ == "__main__":
    main()
